### ISSUE TITLE
Token-transformer TypeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by vanvilecks-not-dead** [tokens-studio/figma-plugin#1998]
**Describe the bug**
I encountered a bug when running the "token-transformer" package from the command-line interface (CLI). The error message displayed is unclear, making it difficult to understand the issue.

**To Reproduce**
1. Synchronise tokens with the project via Github with their entry in the tokens.json file
2. install token-transformer (globally or locally)
3. run `node token-transformer tokens.json output-tokens.json`
4. See this error: 
 
```
{
    value: '{semantic.brand.9}',
    type: 'color',
    '$extensions': { 'studio.tokens': [Object] },
    name: 'semantic.brand.5',
    internal__Parent: 'Dark'
  },
  ... 429 more items

TypeError: Cannot read properties of undefined (reading 'toString')
    at yi (/Users/vanvilecks/.local/share/nvm/v18.14.1/lib/node_modules/token-transformer/dist/transform.js:2:118075)
    at /Users/vanvilecks/.local/share/nvm/v18.14.1/lib/node_modules/token-transformer/dist/transform.js:2:124185
    at Array.filter (<anonymous>)
    at Pi (/Users/vanvilecks/.local/share/nvm/v18.14.1/lib/node_modules/token-transformer/dist/transform.js:2:124158)
    at Ri (/Users/vanvilecks/.local/share/nvm/v18.14.1/lib/node_modules/token-transformer/dist/transform.js:2:124287)
    at /Users/vanvilecks/.local/share/nvm/v18.14.1/lib/node_modules/token-transformer/dist/transform.js:2:137204
    at Ji (/Users/vanvilecks/.local/share/nvm/v18.14.1/lib/node_modules/token-transformer/dist/transform.js:2:137286)
    at transformTokensAndWriteFile (/Users/vanvilecks/.local/share/nvm/v18.14.1/lib/node_modules/token-transformer/cli.js:144:25)
    at transform (/Users/vanvilecks/.local/share/nvm/v18.14.1/lib/node_modules/token-transformer/cli.js:228:13)
[token-transformer] writing tokens to output: tokens-output.json
[token-transformer] done transforming
```
Some fields in the tokens-output.json file with the value "[Object Object]".

**Expected behavior**
it is expected that all fields from tokens.json are converted correctly and there are no fields with [object Object Object]"

**Comment by SamIam4Hyma** [comment]
@jorenbroekema is this still an issue? 
- If so, please remove the archive label. 
- If not, please close/archive the ticket

**Comment by jorenbroekema** [comment]
token-transformer deprecated in favor of using sd-transforms
